---
- name: Converge
  hosts: all
  tasks:
    - name: "Include java"
      include_role:
        name: "java"
#---
#- name: Converge
#  hosts: all
#  tasks:
#    - name: "Include mnt-homeworks-ansible"
#      include_role:
#        name: "mnt-homeworks-ansible"
